# Generated by Django 4.2.26 on 2025-11-22 05:17

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=128, unique=True)),
                ('category', models.CharField(blank=True, max_length=128, null=True)),
                ('uom', models.CharField(help_text='Unit of measure', max_length=64)),
                ('reorder_level', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['sku'], name='catelog_pro_sku_183184_idx'), models.Index(fields=['created_at'], name='catelog_pro_created_c0d57d_idx')],
            },
        ),
    ]
