# Generated by Django 4.2.26 on 2025-11-22 07:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catelog', '0002_category_sku'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='stock',
            name='unique_product_warehouse',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='inventory_s_product_112b63_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='inventory_s_created_913bee_idx',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='stock',
            name='reserved_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='sku',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catelog.sku'),
        ),
        migrations.AddField(
            model_name='stock',
            name='total_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='catelog.sku'),
        ),
    ]
