# Generated by Django 5.2.5 on 2025-11-22 07:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catelog', '0001_initial'),
        ('operations', '0002_order_orderitem_order_operations__created_5d1e92_idx_and_more'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='operations.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='catelog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='warehouse.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['order'], name='operations__order_i_5b1fdf_idx'), models.Index(fields=['product', 'warehouse'], name='operations__product_9d741d_idx')],
            },
        ),
    ]
